### ISSUE TITLE
Add documentation of MongoDB feature.

### ISSUE THREAD

**Issue by bryketos** [17zuoye/pyirt#10]
MongoDB integration is a huge advantage of this repo but is not documented in the Readme.md file.

Please add at least a little bit of documentation about how to use this - this is important for large datasets (e.g. >6GB or over 50,000,000 responses is outside of the memory capability of most laptops and necessitates use of a memory-optimized EC2 instance).

**Comment by junchenfeng** [comment]
Hi, Brian. Thanks for the issue. I will update the readme asap
