### ISSUE TITLE
how to use the pyirt?

### ISSUE THREAD

**Issue by wenfei13693186754** [17zuoye/pyirt#18]
您好，看到您写的这个irt算法，想使用下，可是不知道从哪里下手，不清楚源数据是哪些，都是什么格式，输出数据是什么，是什么格式，希望您有时间可以帮助下，谢谢。

**Comment by junchenfeng** [comment]
In tests.test_model_wrapper, there is a data simulator located in the setUpClass method. If you want to learn to play pyirt (or any python project), start with its tests

**Comment by wenfei13693186754** [comment]
thank you very much!
