### ISSUE TITLE
Add documentation of build process

### ISSUE THREAD

**Issue by bryketos** [17zuoye/pyirt#9]
Add documentation of build process.

For example:

'''
INSTALLATION
To install, please run `python setup.py build` followed by `python setup.py install`.  NOTE: if sudo access is required and system has a different Python than the one you want to use (e.g. Anaconda on Mac OS, Ubuntu, or EC2 with Amazon Linux), you can use `sudo -s` before running `python setup.py install` because just running `sudo python setup.py install` will use the system's Python instead of the user's Python.
'''

**Comment by junchenfeng** [comment]
I think you can submit a pull request for this. I mostly use python setup.py install and it works. So I am not sure what to write about.
